version: '2.2'

services:
  customers-api:
    build: .
    depends_on:
      - customers-db
    ports:
      - "8080:8080"
      - "8000:8000"
  customers-db:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'customersapp251'
    ports:
      - '3306:3306'
